#pragma once

void userInterface();
void userInterfaceUzytkownik();
void userInterfacePracownik(); 
void userInterfaceZarejestrujSie();
void userInterfaceZalogujSie();
void WielokrotnePodanieZlegoHasla();
void ZmianaHasla();
void userInterfaceUzytkownikZalogowany();
void wyswietlDaneU¿ytkownika();
void wyswietlZbior();
void WyszukajKsiazke();
void userInterfacePracownikZarejestrujSie();
void userInterfacePracownikZalogujSie();
void WielokrotnePodanieZlegoHaslaPracownika();
void ZmianaHaslaPracownika();
void wyswietlDanePracownika();
void userInterfacePracownikZalogowany();
void dodajPozycje();
void usunPozycje();
void Zwroc();
void wyswietlZbiorPracownik();